"""a

Revision ID: 3ba74f7456b2
Revises: adbae493b2d2
Create Date: 2020-06-27 11:40:01.761866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ba74f7456b2'
down_revision = 'adbae493b2d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('histories_module', sa.Column('lock_key', sa.Boolean(), nullable=True))
    op.add_column('histories_phase', sa.Column('lock_key', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('histories_phase', 'lock_key')
    op.drop_column('histories_module', 'lock_key')
    # ### end Alembic commands ###
