"""a

Revision ID: 438aaa6f0777
Revises: 3ba74f7456b2
Create Date: 2020-07-01 03:43:08.073658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '438aaa6f0777'
down_revision = '3ba74f7456b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corrections_altatest', sa.Column('answer_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('corrections_altatest', 'answer_id')
    # ### end Alembic commands ###
