"""empty message

Revision ID: 58628d9cec45
Revises: 
Create Date: 2020-06-27 11:20:19.833791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58628d9cec45'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('quesioner', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subjects', 'quesioner')
    # ### end Alembic commands ###
