"""a

Revision ID: 643389584498
Revises: 99f770ee507a
Create Date: 2020-06-19 04:30:45.943835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '643389584498'
down_revision = '99f770ee507a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('altatests', sa.Column('question_sum', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('altatests', 'question_sum')
    # ### end Alembic commands ###
