"""a

Revision ID: 68660abea5ca
Revises: 
Create Date: 2020-07-06 09:11:39.230258

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '68660abea5ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('corrections_quiz')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corrections_quiz',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('history_exam_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('question_quiz_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('answer_quiz_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('is_correct', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['history_exam_id'], ['histories_exam.id'], name='corrections_quiz_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
