"""a

Revision ID: 6b1b9721e407
Revises: 
Create Date: 2020-07-09 05:13:09.741388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b1b9721e407'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('histories_phase', sa.Column('date_certificate', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('histories_phase', 'date_certificate')
    # ### end Alembic commands ###
